Fix auth redirect
vacuumlabs/report-bot pull request #42
Opened 2020-02-21 08:56 UTC by leanil

Set default for env var: REACT_APP_LOGIN_URL

The client expected this env var, and went into a redirect loop
if it wasn't present. Adding it to transenv with the appropriate
default value and reading it from config fixes this problem.

2020-02-21 10:00 UTC, hleumas commented
This seems to work, but it doesn't seem like the right solution. I'd rather understand why isn't the value of REACT_APP_LOGIN_URL present during the build step.

2020-02-21 10:19 UTC, hleumas commented
Ok, so I guess here is the solution, you just need to move the variable to `now.json:build.env`

```
#now.json file

2020-02-21 11:42 UTC, leanil commented
> This seems to work, but it doesn't seem like the right solution. I'd rather understand why isn't the value of REACT_APP_LOGIN_URL present during the build step.

I was puzzled how `.env.production` was loaded into an env var. I didn't realize it's done by react during build, so thanks for pointing that out.

I've found out that now ignores the .env.production file since january, so that's why it broke now.
We could force it to upload the file, but I think your solution is the way to go.

2020-02-21 20:52 UTC, paldys requested changes

2020-02-21 20:52 UTC, paldys commented on now.json
> +            "REACT_APP_LOGIN": "/auth/login"
Don't just copy-paste someone else's suggestion...

This should be `REACT_APP_LOGIN_URL`.

2020-02-24 08:20 UTC, paldys approved these changes

2020-02-24 08:23 UTC, merged